### ISSUE TITLE
webhook通知风格

### ISSUE THREAD

**Issue by asong2022** [helson-lin/ffandown#37]
###  ISSUE Type

- [ ] download failed
- [ ] new features
- [x] style questions
- [ ] other questions

### Download Url

https://bro13cdn.cretech.cn/118619_LxhEk0us/index.m3u8

### Question Details

直播流webhook通知会立刻通知完成下载，估计是第一个ts下载好了就通知完成了，其实直播仍在继续，我也没手动按过中止。

**Comment by asong2022** [comment]
以前是下载完通知，现在好像是开始下载就通知了，，开始下载一个人的群没什么通知必要呀

**Comment by asong2022** [comment]
以前好像是完成才通知，现在变成了开始下载就发通知了

**Comment by helson-lin** [comment]
是的 后续会增加完成通知的 逻辑修改了

---- 回复的原邮件 ----
| 发件人 | ***@***.***> |
| 发送日期 | 2024年05月25日 22:50 |
| 收件人 | helson-lin/ffandown ***@***.***> |
| 抄送人 | Subscribed ***@***.***> |
| 主题 | Re: [helson-lin/ffandown] webhook通知风格 (Issue #37) |

以前好像是完成才通知，现在变成了开始下载就发通知了

**Comment by asong2022** [comment]
> 是的 后续会增加完成通知的 逻辑修改了
> […](#)
> ---- 回复的原邮件 ---- | 发件人 | ***@***.***> | | 发送日期 | 2024年05月25日 22:50 | | 收件人 | helson-lin/ffandown ***@***.***> | | 抄送人 | Subscribed ***@***.***> | | 主题 | Re: [helson-lin/ffandown] webhook通知风格 (Issue #37) | 以前好像是完成才通知，现在变成了开始下载就发通知了 — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you are subscribed to this thread.Message ID: ***@***.***>

好久没来了，请问下现在有下载完成的通知吗~我的还是5.0.8版本

**Comment by helson-lin** [comment]
中秋节假日更新，目前上班比较忙一直没更新。


在 2024年9月14日 ***@***.***> 写道：


是的 后续会增加完成通知的 逻辑修改了
 …
 ---- 回复的原邮件 ---- | 发件人 | @.> | | 发送日期 | 2024年05月25日 22:50 | | 收件人 | helson-lin/ffandown @.> | | 抄送人 | Subscribed @.> | | 主题 | Re: [helson-lin/ffandown] webhook通知风格 (Issue #37) | 以前好像是完成才通知，现在变成了开始下载就发通知了 — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you are subscribed to this thread.Message ID: @.>
好久没来了，请问下现在有下载完成的通知吗~我的还是5.0.8版本

**Comment by helson-lin** [comment]
5.0.9-beta已修复

**Comment by asong2022** [comment]
> 5.0.9-beta已修复

请问下拉取的最新，但是没有之前5.0.8的中止下载的直播中断功能了

**Comment by helson-lin** [comment]
没事的 前端的版本可能有点问题，我晚上看下




在 2024年9月23日 ***@***.***> 写道：


m3u8协议的嘛
 …
 ---- 回复的原邮件 ---- | 发件人 | @.> | | 发送日期 | 2024年09月23日 15:25 | | 收件人 | helson-lin/ffandown @.> | | 抄送人 | helson-lin @.>, State @.> | | 主题 | Re: [helson-lin/ffandown] webhook通知风格 (Issue #37) | 5.0.9-beta已修复 请问下拉取的最新，但是没有之前5.0.8的中止下载的直播中断功能了 — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you modified the open/close state.Message ID: @.***>
是的，而且原来的5.0.8我没删，前台右下角有个更新，我按了一下说已经更新到0.0.9，也没有中止下载的功能了。

**Comment by asong2022** [comment]
> 没事的 前端的版本可能有点问题，我晚上看下 在 2024年9月23日 ***@***.***> 写道： m3u8协议的嘛 … ---- 回复的原邮件 ---- | 发件人 | @.> | | 发送日期 | 2024年09月23日 15:25 | | 收件人 | helson-lin/ffandown @.> | | 抄送人 | helson-lin @.>, State @.> | | 主题 | Re: [helson-lin/ffandown] webhook通知风格 (Issue #37) | 5.0.9-beta已修复 请问下拉取的最新，但是没有之前5.0.8的中止下载的直播中断功能了 — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you modified the open/close state.Message ID: @.***> 是的，而且原来的5.0.8我没删，前台右下角有个更新，我按了一下说已经更新到0.0.9，也没有中止下载的功能了。 — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you modified the open/close state.Message ID: ***@***.***>

谢谢！中止下载的功能特别喜欢
