### ISSUE TITLE
下载失败：Error: spawn /app/lib/ffmpeg EACCES

### ISSUE THREAD

**Issue by chibinyong** [helson-lin/ffandown#57]
以手动安装 ffmpeg 依赖文件和前端依赖，但是下载会提示失败
日志如下：

8ffmpeg error happed Error: spawn /app/lib/ffmpeg EACCES
H    at ChildProcess._handle.onexit (node:internal/child_process:283:19)
6    at onErrorNT (node:internal/child_process:476:16)
U    at process.processTicksAndRejections (node:internal/process/task_queues:82:21) {
  errno: -13,
  code: 'EACCES',
$  syscall: 'spawn /app/lib/ffmpeg',
ath: '/app/lib/ffmpeg',
  spawnargs: [ '-formats' ]
}

**Comment by helson-lin** [comment]
依赖哪里下载的

---- 回复的原邮件 ----
| 发件人 | ***@***.***> |
| 发送日期 | 2024年11月26日 11:46 |
| 收件人 | helson-lin/ffandown ***@***.***> |
| 抄送人 | Subscribed ***@***.***> |
| 主题 | [helson-lin/ffandown] 下载失败：Error: spawn /app/lib/ffmpeg EACCES (Issue #57) |

以手动安装 ffmpeg 依赖文件和前端依赖，但是下载会提示失败
日志如下：

8ffmpeg error happed Error: spawn /app/lib/ffmpeg EACCES
H at ChildProcess._handle.onexit (node:internal/child_process:283:19)
6 at onErrorNT (node:internal/child_process:476:16)
U at process.processTicksAndRejections (node:internal/process/task_queues:82:21) {
errno: -13,
code: 'EACCES',
$ syscall: 'spawn /app/lib/ffmpeg',
ath: '/app/lib/ffmpeg',
spawnargs: [ '-formats' ]
}

**Comment by chibinyong** [comment]
> 依赖哪里下载的
> […](#)
> ---- 回复的原邮件 ---- | 发件人 | ***@***.***> | | 发送日期 | 2024年11月26日 11:46 | | 收件人 | helson-lin/ffandown ***@***.***> | | 抄送人 | Subscribed ***@***.***> | | 主题 | [helson-lin/ffandown] 下载失败：Error: spawn /app/lib/ffmpeg EACCES (Issue #57) | 以手动安装 ffmpeg 依赖文件和前端依赖，但是下载会提示失败 日志如下： 8ffmpeg error happed Error: spawn /app/lib/ffmpeg EACCES H at ChildProcess._handle.onexit (node:internal/child_process:283:19) 6 at onErrorNT (node:internal/child_process:476:16) U at process.processTicksAndRejections (node:internal/process/task_queues:82:21) { errno: -13, code: 'EACCES', $ syscall: 'spawn /app/lib/ffmpeg', ath: '/app/lib/ffmpeg', spawnargs: [ '-formats' ] } — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you are subscribed to this thread.Message ID: ***@***.***>

你教程里面提供的地址 https://github.com/ffbinaries/ffbinaries-prebuilt/releases
cpu是8505 docker启动的 下载的依赖为ffmpeg-6.1-linux-64.zip、ffprobe-6.1-linux-64.zip

**Comment by helson-lin** [comment]
你没有给权限吧

---- 回复的原邮件 ----
| 发件人 | ***@***.***> |
| 发送日期 | 2024年11月26日 11:53 |
| 收件人 | helson-lin/ffandown ***@***.***> |
| 抄送人 | helson-lin ***@***.***>,
Comment ***@***.***> |
| 主题 | Re: [helson-lin/ffandown] 下载失败：Error: spawn /app/lib/ffmpeg EACCES (Issue #57) |

依赖哪里下载的
…
---- 回复的原邮件 ---- | 发件人 | @.> | | 发送日期 | 2024年11月26日 11:46 | | 收件人 | helson-lin/ffandown @.> | | 抄送人 | Subscribed @.> | | 主题 | [helson-lin/ffandown] 下载失败：Error: spawn /app/lib/ffmpeg EACCES (Issue #57) | 以手动安装 ffmpeg 依赖文件和前端依赖，但是下载会提示失败 日志如下： 8ffmpeg error happed Error: spawn /app/lib/ffmpeg EACCES H at ChildProcess._handle.onexit (node:internal/child_process:283:19) 6 at onErrorNT (node:internal/child_process:476:16) U at process.processTicksAndRejections (node:internal/process/task_queues:82:21) { errno: -13, code: 'EACCES', $ syscall: 'spawn /app/lib/ffmpeg', ath: '/app/lib/ffmpeg', spawnargs: [ '-formats' ] } — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you are subscribed to this thread.Message ID: @.>

你教程里面提供的地址 https://github.com/ffbinaries/ffbinaries-prebuilt/releases
cpu是8505 docker启动的 下载的依赖为ffmpeg-6.1-linux-64.zip、ffprobe-6.1-linux-64.zip

**Comment by helson-lin** [comment]
点击链接加入群聊【FFandown反馈群】：http://qm.qq.com/cgi-bin/qm/qr?_wv=1027&k=WFpPUn1uEqEwUsqgJ32m-JKx5BkDxghX&authKey=KmQXl3IHvULOVHUtCGvCOHqhtKg8ENtoP0BbLesFFhQXZvT%2BgfkaDXYha6DgDnkx&noverify=0&group_code=953172983

---- 回复的原邮件 ----
| 发件人 | ***@***.***> |
| 发送日期 | 2024年11月26日 11:53 |
| 收件人 | helson-lin/ffandown ***@***.***> |
| 抄送人 | helson-lin ***@***.***>,
Comment ***@***.***> |
| 主题 | Re: [helson-lin/ffandown] 下载失败：Error: spawn /app/lib/ffmpeg EACCES (Issue #57) |

依赖哪里下载的
…
---- 回复的原邮件 ---- | 发件人 | @.> | | 发送日期 | 2024年11月26日 11:46 | | 收件人 | helson-lin/ffandown @.> | | 抄送人 | Subscribed @.> | | 主题 | [helson-lin/ffandown] 下载失败：Error: spawn /app/lib/ffmpeg EACCES (Issue #57) | 以手动安装 ffmpeg 依赖文件和前端依赖，但是下载会提示失败 日志如下： 8ffmpeg error happed Error: spawn /app/lib/ffmpeg EACCES H at ChildProcess._handle.onexit (node:internal/child_process:283:19) 6 at onErrorNT (node:internal/child_process:476:16) U at process.processTicksAndRejections (node:internal/process/task_queues:82:21) { errno: -13, code: 'EACCES', $ syscall: 'spawn /app/lib/ffmpeg', ath: '/app/lib/ffmpeg', spawnargs: [ '-formats' ] } — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you are subscribed to this thread.Message ID: @.>

你教程里面提供的地址 https://github.com/ffbinaries/ffbinaries-prebuilt/releases
cpu是8505 docker启动的 下载的依赖为ffmpeg-6.1-linux-64.zip、ffprobe-6.1-linux-64.zip

**Comment by chibinyong** [comment]
总结下 资源问题，资源下载要翻墙
